# Generated by Django 4.2.7 on 2023-11-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('style_id', models.CharField(max_length=50)),
                ('art_style', models.CharField(max_length=50)),
                ('aspect_ratio', models.CharField(max_length=10)),
                ('high_res', models.BooleanField(default=False)),
                ('generated_image', models.ImageField(upload_to='generated_images/')),
            ],
        ),
    ]
