# Generated by Django 4.2.7 on 2023-11-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelfPrompt', '0002_artprompt_frame_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='artprompt',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True),
        ),
    ]
