# Generated by Django 4.2.7 on 2023-11-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelfPrompt', '0004_artprompt_watermarked_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artprompt',
            name='frame_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
